#!/bin/bash

(( $# >= 1 )) || {
	echo "usage: bench-log MESSAGE" >&2
	exit 1
}

conf_dir="$HOME/.bench"
mkdir -p "${conf_dir}" || exit 1
pipe="${conf_dir}/bench"

[[ -p "$pipe" ]] || {
	mkfifo "$pipe" || exit 1
}

echo "Sending log message to benchmark: '$*'"
echo "log $*" > "$pipe"
