#!/bin/bash

(( $# >= 1 )) || {
	echo "usage: bench-update UPDATE_MESSAGE" >&2
	exit 1
}

conf_dir="$HOME/.bench"
mkdir -p "${conf_dir}" || exit 1
pipe="${conf_dir}/bench"

[[ -p "$pipe" ]] || {
	mkfifo "$pipe" || exit 1
}

echo "Scheduling benchmark script update (on next loop start)."
echo "update" > "$pipe"
echo "log update message: $*" > "$pipe"
