#!/bin/bash

mountpoint -q "/mnt/cephfs" || {
	echo "error: /mnt/cephfs is not mounted" >&2
	exit 1
}

blob="$(ls -1v "/mnt/cephfs/blobs" | head -1)" || exit 1
[[ -d "/mnt/cephfs/blobs/$blob" ]] || {
	echo "error: blob dir '/mnt/cephfs/blobs/$blob' does not exist" >&2
	exit 1
}

mountpoint -q "/mnt/adm/cephfs" || {
	echo "error: /mnt/adm/cephfs not mounted" >&2
	exit 1
}

snap="$(ls -1v "/mnt/adm/cephfs/.snap" | head -1)" || exit 1
[[ -d "/mnt/adm/cephfs/.snap/$snap" ]] || {
	echo "error: snap dir '/mnt/adm/cephfs/.snap/$snap' already exists" >&2
	exit 1
}

(( blob <= snap )) && echo "$blob" || echo "$snap"
